db:
#    poolName: jwd-mysql-pool-datariver
  driverClassName: com.mysql.jdbc.Driver
  jdbcUrl: jdbc:mysql://localhost:3306/cap?characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
  username: root
  password: 100793ln
